version: '3'

services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-5.0.3
    restart: always
    environment:
      - DB_SERVER_HOST=mysql-server  #MySQL ip
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=mypasswd
      - MYSQL_DATABASE=zabbix
    ports:
      - "10051:10051"
    user: root

  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0.3
    restart: always
    depends_on:
      - zabbix-server
    environment:
      - DB_SERVER_HOST=mysql-server     #MySQL ip
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=mypasswd
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=Asia/Shanghai
      - ZBX_SERVER_HOST=zabbix-server   #zabbix-server服务器ip
      - ZBX_SERVER_PORT=10051
    #    volumes:
    ports:
      - "8090:8080"
    user: root
